spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/LibraryManagement
    username: postgres
    password: 1234
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
       
logging:
  level:
    root: info  # Set the default logging level
   
